language: bash

services:
  - docker

env:
  matrix:
    - ALPINE_VER=3 TAGS=latest
    - ALPINE_VER=3 TAGS=dev ALPINE_DEV=1

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
